### PR TITLE
Rename bower.json to .bower.json

### PR DESCRIPTION
**Pull request by Jinkwon**
Bower need .bower.json, not bower.json
Please change this name.

Thanks.

### CODE REVIEW

**Comment by agershun** [comment]
I did it manually in develop branch. Thank you!

**Comment by agershun** [comment]
I just registered AlaSQL as a Bower package. May I ask you to verify, how it is installed?

**Comment by Jinkwon** [comment]
@agershun 
It works fine. :) 
Thanks.



BTW, I think should have added some more ignore property to .bower.json.
Bower will download full codes, it is too heavy as well.

**Comment by agershun** [comment]
Thank you! 
I have never used bower before. Can you explain:
1. Can I include in the package only one directory with 'dist'?
* /dist

2. Do I have to include node_modules as well? AlaSQL uses only XLSX package for Excel import-export procedures

3. Do I need to include .bower file?

**Pull request closed without merging**
