### PR TITLE
JOIN USING compatibility with String and Number objects

### PR DESCRIPTION
**Pull request by akhaneev**
P.S. there is still incompatibility of operators like IN with String and Number objects. These operators use Array.indexOf() function which fails on String and Number objects. Maybe you have an idea of how it can be fixed?

### CODE REVIEW

**Comment by mathiasrw** [comment]
Thank you!

**Comment by mathiasrw** [comment]
> P.S. there is still incompatibility of operators like IN with String and Number objects. These operators use Array.indexOf() function which fails on String and Number objects. Maybe you have an idea of how it can be fixed?

Do you mean when you have `new String("abc")` as `name` and then do a `... where name in ('john', 'simon')`?

**Comment by akhaneev** [comment]
Yes, exactly.

**Comment by mathiasrw** [comment]
Released as part of version 0.6.4

**Pull request merged**
