### PR TITLE
Implement TRIGGER AFTER DELETE

### PR DESCRIPTION
**Pull request by AndreHeber**
I've implemented the feature to trigger a function after DELETE. There is no information about the change itself, only that it is changed. But that is exactly what I need in my own project.

### CODE REVIEW

**Comment by AndreHeber** [comment]
This is strange. `npm test` just runs fine!

**Comment by kanghj** [comment]
@AndreHeber, I think you have to commit the contents of the `dist` directory too!

**Comment by mathiasrw** [comment]
@AndreHeber Its because the test runs both from dist and from src (to make sure we dont push something that does not have build src)

I merge the change and build from src to make it all good...

**Comment by AndreHeber** [comment]
Ah, nice.
It is my first pull-request, I'm happy now. 😀
And next time, I will commit dist too.
Thank you!

**Comment by mathiasrw** [comment]
💃

**Pull request merged**
