### PR TITLE
Fixed incorrect exception

### PR DESCRIPTION
**Pull request by a-gorbunov**
Simple grammar error fix.
Sorry, couldn't add test ("npm test" throws an error on Windows7).
Thanks for a great job.

### CODE REVIEW

**Comment by agershun** [comment]
Spasibo!

**Comment by agershun** [comment]
Tests work fine.

**Comment by a-gorbunov** [comment]
http://prntscr.com/9v6em0

**Comment by agershun** [comment]
I usually use:
```
> cd test
> mocha .
```
I will @mathiasrw about this ```npm test``` problem

**Comment by a-gorbunov** [comment]
Got it. Tests are running. But got 5 fails
```
1) Test 238 Test from string and into string 1. JSON:
2) Test 238 Test from string and into string 2. CSV() and AS:
3) Test 238 Test from string and into string 3. XLSX:
4) Test 242 Multi-columns Excel file 1. Read multi-column file:
5) Test 242 Multi-columns Excel file 2. Read multi-column file:
```
All with similar error:
```
     Error: ENOENT: no such file or directory, open 'C:\UsersUserDesktopTelecomalasql  est\test238.json'
      at Error (native)
      at Object.fs.openSync (fs.js:549:18)
      at Object.fs.writeFileSync (fs.js:1156:15)
      at Object.utils.saveFile (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:3441:23)
      at Object.alasql.into.JSON (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:13811:21)
      at eval [as intoallfn] (eval at <anonymous> (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:6811:22), <anonymous>:3:33)
      at queryfn3 (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:6102:19)
      at queryfn (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:5817:12)
      at statement (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:6819:14)
      at Function.alasql.dexec (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:4160:27)
      at Function.alasql.exec (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:4111:17)
      at alasql (C:\Users\User\Desktop\Telecom\alasql\dist\alasql.js:120:18)
      at Context.<anonymous> (C:\Users\User\Desktop\Telecom\alasql\test\test238.js:15:9)
      at callFnAsync (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:8)
      at Test.Runnable.run (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
      at Runner.runTest (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:10)
      at C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:14)
      at C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7
      at next (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:283:14)
      at Immediate._onImmediate (C:\Users\User\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)
```

Should I open an issue?

**Comment by agershun** [comment]
Yes, please. I testes the tests only with Windows 8.1 and OSX)

**Pull request merged**
