### PR TITLE
Invalid query throws n.Term #1871

### LINKED ISSUE #1871: Invalid query throws `n.Term is not a constructor`
I've noticed that the error message on the invalid token looks like this:

> n.Term is not a constructor

When executing:

```
> xxxx
```

It looks like the invalid token is not handled and it just throws an unhandled exception.

You can see this on my Terminal App:

https://codepen.io/jcubic/pen/dVBaRm

### PR DESCRIPTION
**Pull request by vishal6557**
Fix #1871 

Thank you for the time you are putting into AlaSQL!

### CODE REVIEW

**Comment by vishal6557** [comment]
@mathiasrw  Have a look, any feedback is appreciated!

**Comment by mathiasrw** [comment]
Very interesting how you solved this. Im wondering why the `yy.Term` was there in the first place. 

Ill merge it. 

Did you have any problem generating the file from the jison? I had some challenges with deep dependencies lately. Or did you just update the actual .js file?

**Comment by mathiasrw** [comment]
Fix released as part of v4.3.1

**Comment by vishal6557** [comment]
@mathiasrw No, I don't have a problem generating files from the `jison`

I think `yarn jison` command is broken, I manually install `jison` globally and using command 
`jison ./src/alasqlparser.jison -o ./src/alasqlparser.js`

Can you try this command if it works, I'll create a pull request and update the `package.json`

**Comment by mathiasrw** [comment]
Neat! Ill look into this!

**Comment by mathiasrw** [comment]
It works. Neat!

**Pull request merged**
