### PR TITLE
fixes #1666, SUM(FUNC(x)) is BROKEN since 2.2.0

### LINKED ISSUE #1666: SUM(FUNC(x)) is BROKEN since 2.2.0
Tested SUM(FLOOR(col) and it is not running FLOOR or CEIL or ROUND or anything inside SUM ever since version 2.2.0 release.
It's working fine in 2.1.8 all versions after that are not working for this use-case.

### PR DESCRIPTION
**Pull request by rrameshkumar76**
Fixes #1666, SUM(FUNC(x)) that's is broken since 2.2.0

I changed the max code to match min code. That is why its a bit longer now.

### CODE REVIEW

**Comment by rrameshkumar76** [comment]
All current tests work and I have added a new test file for the fix.

**Comment by mathiasrw** [comment]
Thank you!

**Comment by rameshrajagopalanbayer** [comment]
Thanks @mathiasrw  for merging this PR.

**Comment by mathiasrw** [comment]
Released as part of v4.1.7

**Pull request merged**
