### PR TITLE
Postgres-specific aliases and fixes

### PR DESCRIPTION
**Pull request by bopjesvla**
Adds ~ as an alias for REGEXP, \~~ and \~~* for LIKE, and !~~ and !~~* for NOT LIKE, see https://www.postgresql.org/docs/9.3/static/ddl-constraints.html.

Also, pg_dump adds some weird unnecessary conversions of obscure types, which is why I turned conversions to unknown types into noops.

### CODE REVIEW

**Comment by mathiasrw** [comment]
This is great!

I can see you added 11 lines that is never reached by a test  scenario.

Can I ask you to make a new test file in `test/` asserting the new behavour? 

This way we can eliminate future problems by someone accidently breaking the functionality.  Have a look at https://github.com/agershun/alasql/blob/develop/test/test000.js to see an example.

**Comment by bopjesvla** [comment]
Done!

**Comment by bopjesvla** [comment]
I'm guessing that those 8 lines are lines I moved which didn't have tests before.

**Comment by mathiasrw** [comment]
You are awesome - thank you so much...

**Pull request merged**
