### PR TITLE
Add GETDATE, NOW as alias to parser + allow CURRENT_TIMESTAMP with parenthesis

### PR DESCRIPTION
**Pull request by paulrutter**
Add the following functions to the parser:
- NOW
- GETDATE

Also add `CURRENT_TIMESTAMP()` to the parser (with parenthesis).

- Adjust failing test as `now` is a reserved keyword. It was already, it was just not validated.
- Add test

See #1979 

Thank you for the time you are putting into AlaSQL!

### CODE REVIEW

**Comment by paulrutter** [comment]
@mathiasrw whenever you have time, could you please check out this PR? Thanks.

**Comment by mathiasrw** [comment]
Hi Paul.  I _really_ like what you did here. Thank you so much. This is probably how we should have done it from the beginning. 

The changes in [test/test845.js](https://github.com/AlaSQL/alasql/pull/1980/files#diff-9c3bce042e0e355f3ef04987c07438ad14f7b3099064177ac0b0484daf553b46) indicate that this is a breaking change so I will bundle this into a bucket of changes waiting for us to bump major version. Probably during the next few months as we are in the work of restructuring the whole source into ES6 friendly components.

**Comment by paulrutter** [comment]
@mathiasrw Thanks, good to know that will take a while for this to get into a release.
Since we're making changes on this front, it might be worthwhile to also add all other date functions in the same matter (see https://github.com/AlaSQL/alasql/pull/1937#issuecomment-2198488165).

Do you agree? If so, i could work on a PR (WiP: https://github.com/AlaSQL/alasql/compare/develop...blueconic:alasql:feature/add-all-date-functions-to-parser?expand=1)

**Comment by mathiasrw** [comment]
@paulrutter We are talking about all fields named DATE/NOW/GETDATE/YEAR/MONTH having to be wrapped in escape chars, right?

**Comment by paulrutter** [comment]
@mathiasrw yes, indeed. In backticks/quotes.

**Comment by paulrutter** [comment]
@mathiasrw See https://github.com/AlaSQL/alasql/pull/1982 for additional work on the parser.
One can still use `YEAR`, `MONTH` etc without escape chars in `DATEADD` for example, although one cannot use it as column alias without escape characters.

**Comment by paulrutter** [comment]
Closed in favor of #1982

**Comment by mathiasrw** [comment]
Sooooo, this one is to be closed?

**Comment by paulrutter** [comment]
@mathiasrw this was more the issue related to the original PR (#1980), which i closed.
We can close this issue, but then we also have the new PR #1982 still open (which is fine to me).

**Pull request closed without merging**
