### PR TITLE
Adds BETWEEN op scenario to the toString prototype for yy.Ops class

### PR DESCRIPTION
**Pull request by sljohnsondev**
Adds check for BETWEEN op and provides toString logic.

Resolves https://github.com/agershun/alasql/issues/975

### CODE REVIEW

**Comment by mathiasrw** [comment]
Nice one! Thank you :)

Im working on making the tests flow again.

**Comment by mathiasrw** [comment]
Has been released as part of v0.6.1

**Comment by sljohnsondev** [comment]
Awesome!  Thank you so much, Mathias!

**Comment by sljohnsondev** [comment]
@mathiasrw I totally missed the NOT BETWEEN scenario here...was too focused on the specific language of the Jira ticket I was working on and should have taken a moment to think through this more.  Pushing another PR shortly.  Apologies for the miss on my end.

**Comment by mathiasrw** [comment]
@sljohnsondev All good. Thank you for noticing. I should have been more focused on the test too.

**Pull request merged**
