### PR TITLE
Fix electron compatibility

### PR DESCRIPTION
**Pull request by martinstarman**
This PR partially revert changes in alasql-worker.js - commit 91ed634.

I have an app written in [electron](https://github.com/electron/electron). Until version 0.2.5 everything works well. From 0.2.6 alasql does not work in electron anymore.

Because electron is packaged chrome this condition
```js
if(typeof location !== "undefined" && location.reload && !(typeof process !== "undefined" && process.browser) && !(typeof require === "function" && typeof require.specified === "function")) {
```
will evaluate into Uncaught ReferenceError: alasql is not defined on this line 
```js
alasql.worker = function(path, paths, cb) {
``` 

This PR fix that. More info http://electron.atom.io/

### CODE REVIEW

**Comment by mathiasrw** [comment]
Tank you so much for taking the time to contribute. 

Its not really good that the changes from 91ed634 are roled back - cause there was a reason we changed it (cant find the issue right now).

I would much rather work with you to see how we can get electron to work by pinning out the exact place the code fails. 

Would it be possible for you to let me know how to build the simplest code that replicates the issue?

**Comment by mathiasrw** [comment]
Woooow - it took me 1 hour to make my first .dmg installer that could open my calculator from a bootstrap interface. 

Lets get electron supported as fast as possible !

I have to do some tests, but I have a feeling the best way of dealing with it is to `require('alasql')` and then ask it to run as a a webworker with `alasql.worker();` instead of including alasql-worker.js 

```js
alasql = require('alasql')
alasql.worker();
alasql.promise('SELECT VALUE 1+1)
         .then((data)=>{
                console.log(data);
         }).catch((err)=>{
           console.log('Error:', err);
      });
```

Its described as "Option 2" on the wiki for using AlaSQL as a webworker https://github.com/agershun/alasql/wiki/Webworker#option-2

Would this solve your issue?

**Comment by martinstarman** [comment]
Thanks for the quick response. It took me some time to try it but it looks like solution!

**Comment by mathiasrw** [comment]
Thanks for a very good description. Have to try tonight. 

Have you done a `npm install alasql` ?

**Comment by martinstarman** [comment]
Yes, I have alasql as dependency and node_modules contains alasql folder with this files
```
$ ls -l
total 73
-rw-r--r-- 1 Martin 197121 23644 Jul 20 07:39 CHANGELOG.md
-rw-r--r-- 1 Martin 197121  1497 Jul 20 07:39 LICENSE
-rw-r--r-- 1 Martin 197121 22260 Jul 20 07:39 README.md
drwxr-xr-x 1 Martin 197121     0 Jul 20 07:39 bin
drwxr-xr-x 1 Martin 197121     0 Jul 20 07:39 dist
drwxr-xr-x 1 Martin 197121     0 Jul 20 07:39 node_modules
-rw-r--r-- 1 Martin 197121  1199 Jul 20 07:39 package.js
-rw-r--r-- 1 Martin 197121  3652 Jul 20 07:39 package.json
-rw-r--r-- 1 Martin 197121   123 Jul 20 07:39 tslint.json
drwxr-xr-x 1 Martin 197121     0 Jul 20 07:39 utils
```

**Comment by martinstarman** [comment]
Related #388

**Comment by abruneau** [comment]
Hello,

do you know when this fix will be part of the master branch ?
I really need it to build my app.

Thank you

**Comment by mathiasrw** [comment]
Hello awesome electron people. 

This pullrequest will not be implemented as it created problems for webpack. 

But version 0.3.0 has just been released - and it does not give any errors and it can spit out results - so its working :)

does any of you know how to deal with webworkers in the electron context? Normally a script path is required to start the webworker but as things are required I cant see how to pass a path to the node_module .js source

**Comment by abruneau** [comment]
I tried to update to alasql 3.0 and I have the same issue

**Comment by mathiasrw** [comment]
Thanks for feedback. Really Strange. 

Could you try to delete the node_module folder and do a NPM install ?

If thr does not work I Will make a demo repo of how I Got it to work

**Comment by abruneau** [comment]
It steel doesn't work. 
I moved back to pure js.

**Comment by mathiasrw** [comment]
@abruneau 

I can make it work with version 0.3.0. 

Please make sure you dont have `"alasql": "^0.2.7"` in some `package.json` file.

**Comment by martinstarman** [comment]
Everything is working again for me with 0.3.0. Thanks!

**Pull request closed without merging**
