### PR TITLE
Added the missing NOT LIKE operator

### PR DESCRIPTION
**Pull request by gregaubert**
The NOT LIKE operator was missing. I added it to my fork, here is a pull request if you want to merge it to your repos.

### CODE REVIEW

**Comment by agershun** [comment]
Aubert. hi! Thank you for modifications. 

I think, we can modify grammar file to replace line:
```
    NOT LIKE    return 'NOT_LIKE'
```
to 
```
    NOT\sLIKE return 'NOT_LIKE'
```
to allow more than one space between NOT and LIKE.

In this case these lines should be inserted before:
```
    \s         return;
```

I will merge your pull requrest tonight and will check. Unfortunately, I have no big experience in merging.

Andrey

**Comment by gregaubert** [comment]
Ah yes, good idea, and the same should be done for NOT BETWEEN then.
You want me to update the pull request with it ?

**Comment by agershun** [comment]
Exactly!

Could you write update and I will apply it?

Отправлено с iPhone

**Comment by gregaubert** [comment]
Okay I'll do it now

**Comment by agershun** [comment]
Merged and recompiled. Thank you!

**Pull request merged**
