### PR TITLE
Adds NOT BETWEEN scenario to yy.Op.toString() logic

### PR DESCRIPTION
**Pull request by sljohnsondev**

### CODE REVIEW

**Comment by mathiasrw** [comment]
😂👍

**Comment by sljohnsondev** [comment]
@mathiasrw this isn't that urgent for us but curious to know when you think this change will get released?  Thank you!  Hope you have a nice weekend!

**Comment by mathiasrw** [comment]
Ohhh - I forgot to release! 

Its out now as 0.6.2

**Comment by sljohnsondev** [comment]
No problem at all! Thank you again!

**Pull request merged**
