### PR TITLE
#527 Changed window to self

### PR DESCRIPTION
**Pull request by nickdeis**
#527 Changed window to self. Probably should do this elsewhere

### CODE REVIEW

**Comment by agershun** [comment]
I affarid that we need to do it more globally, then just in this function. We can start AlaSQL initiation with determination of mode/environment like: 
* Node / browser / worker / vm / others

And more, ```self``` occasionally has ```window``` value, I think it is a side effect, so we can have global variable, like: ```alasql.mode``` or ```alasql.global``` to keep globals.

**Comment by nickdeis** [comment]
This will always return the global
```javascript
Function('return this')()
```
Doesn't work with CSP, which is gaining some traction, but you can reenable eval through directives.

**Comment by nickdeis** [comment]
[getGlobal|https://jsfiddle.net/3wrman1p/] inspired by [System.global|https://github.com/tc39/proposal-global]

**Comment by agershun** [comment]
:+1: I will analyze it tonight. Thank you for great idea!

**Comment by nickdeis** [comment]
Cool, I'll close this for now.

**Comment by nickdeis** [comment]
I would also argue that the problem of getting global and finding out which env alasql is in are dependent. Env have only one thing in common: certain native functions on the global scope.
[Here's an attempt at figuring out which env alasql is in|https://jsfiddle.net/3wrman1p/1/]

**Comment by agershun** [comment]
Let's open new issue and solve this problem in complex.

**Pull request closed without merging**
