### PR TITLE
[WIP] CREATE VIEW error with localStorage engine #604

### PR DESCRIPTION
**Pull request by positively4th**
Some changes to get select from view to work with localStorage. New test case shows more problems with localStorage.

Hopefully I have not missunderstod it completly:-)

### CODE REVIEW

**Comment by mathiasrw** [comment]
Did you do a `npm test` on your local machine?

I can see the 2 news tests are failing: https://travis-ci.org/agershun/alasql/jobs/119388243 

```
Test 604 - CREATE VIEW error with localStorage engine #604 * Reselect from table:
      AssertionError: false == true
      + expected - actual
      -false
      +true
      
      at Context.<anonymous> (test604.js:99:2)
  2) Test 604 - CREATE VIEW error with localStorage engine #604 * Reselect from view:
     TypeError: alasql.databases[source.databaseid].tables[source.tableid].select is not a function
      at Object.source.datafn (/home/travis/build/agershun/alasql/dist/alasql.js:7293:73)
      at /home/travis/build/agershun/alasql/dist/alasql.js:5969:19
      at Array.forEach (native)
      at queryfn (/home/travis/build/agershun/alasql/dist/alasql.js:5966:16)
      at statement (/home/travis/build/agershun/alasql/dist/alasql.js:6988:14)
      at Function.alasql.dexec (/home/travis/build/agershun/alasql/dist/alasql.js:4252:11)
      at Function.alasql.exec (/home/travis/build/agershun/alasql/dist/alasql.js:4234:17)
      at alasql (/home/travis/build/agershun/alasql/dist/alasql.js:120:18)
      at /home/travis/build/agershun/alasql/dist/alasql.js:4426:9
      at lib$es6$promise$$internal$$initializePromise (/home/travis/build/agershun/alasql/node_modules/es6-promise/dist/es6-promise.js:408:9)
      at new lib$es6$promise$promise$$Promise (/home/travis/build/agershun/alasql/node_modules/es6-promise/dist/es6-promise.js:581:60)
      at promiseExec (/home/travis/build/agershun/alasql/dist/alasql.js:4425:10)
      at Function.alasql.promise (/home/travis/build/agershun/alasql/dist/alasql.js:4469:10)
      at Context.<anonymous> (test604.js:104:9)
```

**Comment by positively4th** [comment]
Hi,

I did the fix but realized that reinitializing the view from localstorage
would be be tricky, so I included tests for that also. In doing so I
realized that I could neither restore the view nor the table from
localstorage. The two test errors show exactly that.

I did not go on to fix the test errors beacuase:

1. I'm surprised that restoring the table does not work. Did I do something
wrong.

2. From my limited understanding of the code base it seems tricky to save
and restore the view (I can give you more details but I would like to sort
out the previous point first).

Understand what I  mean?

Regards

Den ons 30 mars 2016 07:40Mathias Rangel Wulff <notifications@github.com>
skrev:

**Comment by mathiasrw** [comment]
I see - you added the test to show its not working. 

If you can please replace ´`it` with `it.skip` for the new tests you made that are not working we can merge your changes in and keep an issue open to fix it.

**Comment by positively4th** [comment]
Sure, but I was a bit worried about the changes. I do not see the big picture here and I'm not sure I did not break anything.

The changes in src/60createtable.js looks ok to me. However changes in src/420from.js I'm a bit worried that something will break:-)

**Comment by mathiasrw** [comment]
Thats ok. 

That is why we (try to) have all functionality in the tests - so that if you break something an old test will fail.

So... as long as you are only skipping tests you yourself wrote there is no problem (other than the fact that there is a bug...)

**Pull request merged**
