### PR TITLE
Resolve #933: Tabletop reads in empty cells as numeric 0 instead of empty string

### LINKED ISSUE #933: Tabletop reads in empty cells as numeric 0 instead of empty string
Replicating code:

https://jsfiddle.net/oh0m5d85/

Spreadsheet used in code

https://docs.google.com/spreadsheets/d/1KF0w8f0pvoetEDcnE3VNPiE7QLhtadMMcfxn7q2u11Y/edit#gid=0

This is a big problem for me because I've been using handlebars to present the data alasql returns as html, and all those ugly zeroes really drive me nuts.

I would try solving the problem with a pull request, but I'm new to the javascript world and know nothing about how things are packaged, tested, versioned, and published.

I am currently suspecting this commit for causing this behavior:
https://github.com/agershun/alasql/commit/ee7c4afa250f4271bcafe6572ecbe7e17f125ca2

And I think this is not the way to properly handle numbers: I checked tabletop's documentation (today), and they have a special init option that allows converting numbers automatically. It is off by default, but if I'm reading the code right, alasql allows passing additional init options to tabletop. So the changes in that commit should nolonger be necessary.

Again, I'm new to github and opensource development. Please tell me if I'm formatting anything wrong, and I would deeply appreciate it if someone could tell me how this project works and how I could have fixed this with a pull request.

I really love alasql and would like to contribute.

### PR DESCRIPTION
**Pull request by renxida**
Reverts commit ee7c4afa250f4271bcafe6572ecbe7e17f125ca2. In the future, use argument `parseNumbers` to the tabletop function to process numbers as numeric types.

(Also, should I be changing the version number somewhere?)

### CODE REVIEW

**Comment by mathiasrw** [comment]
Looks good. 

Please ignore the version number. 

For tabletop to work you might need to do a `npm install tabletop --save-dev` so that the correct dependency can be written to package.json - and mocha should then know how to access it. 

Please try and push changes to your own branch - that will make the tests rerun

**Comment by renxida** [comment]
Hmmm. Travis buids fail because it runs `npm run test:only` before `npm run test`, which tests the old version of alasql without running gulp to do the updated script. What do I do?

**Comment by mathiasrw** [comment]
Please commit the dist/ dir too

**Comment by renxida** [comment]
Bump. Branch ready to merge.

**Comment by renxida** [comment]
Bump. Somebody merge this.

**Pull request merged**
