### PR TITLE
Autoincrement for local storage

### PR DESCRIPTION
**Pull request by kanghj**
http://jsfiddle.net/80smosgp/2/ should show that it works as expected. 

This is really @seb-ster 's code provided in the issue thread #462

### CODE REVIEW

**Comment by kanghj** [comment]
@mathiasrw, I'll probably need help on the tests. This scenario here only affects localstorage, but all the tests seem to be running in a node environment, how do I test local storage specific code?

**Comment by mathiasrw** [comment]
Of cause...

I suggest you do a 

    npm install --save-dev node-localstorage

and make a test that starts with

````
if (typeof localStorage === "undefined" || localStorage === null) {
  var LocalStorage = require('node-localstorage').LocalStorage;
  localStorage = new LocalStorage('./testxxx.localstorage');
}
```

Then everything should work :)

**Comment by kanghj** [comment]
@mathiasrw, I have modified an existing test to only pass with the modifications added in this PR. Looks like there was support for writing LocalStorage tests in alasql already after all! Very cool. Unfortunately, there are other places where autoincrement for locastorage ought to work, but somehow still isn't (e.g. test389 when AUTOCOMMIT is off), I'll investigate them.

**Comment by mathiasrw** [comment]
Let me know when to merge the PR

**Comment by mathiasrw** [comment]
Any news on this?

**Comment by kanghj** [comment]
Sorry, I got a bit busier than expected and this was a little harder to track down than I thought... Perhaps let's merge this PR first, but not close the issue. I'll work on this sometime next weekend when I have more time.

**Pull request merged**
